// Fixture for: iphone_15_pro_fixture
// Generated by Kim Formlabs Bot
// Operation: soldering

// Dimensions
object_length = 146.60;
object_width = 70.60;
object_height = 8.25;
wall_thickness = 3.00;
base_height = 10.00;
clearance = 10.00;

// Calculated
total_length = object_length + wall_thickness * 2 + clearance * 2;
total_width = object_width + wall_thickness * 2 + clearance * 2;
total_height = object_height + base_height + wall_thickness;

module object_cutout() {
    translate([wall_thickness + clearance, 
               wall_thickness + clearance, 
               base_height])
        cube([object_length, object_width, object_height + 1]);
}

module grip_cutouts() {
    // Side access cutouts
    translate([total_length/2 - 10, -1, base_height + object_height/2])
        cube([20, total_width + 2, 10]);
    
    // Front/back access
    translate([-1, total_width/2 - 10, base_height + object_height/2])
        cube([total_length + 2, 20, 10]);
}

module fixture() {
    difference() {
        // Main block
        cube([total_length, total_width, total_height]);
        
        // Object cavity
        object_cutout();
        
        // Tool access
        grip_cutouts();
        
        // Text label
        translate([total_length/2, total_width/2, total_height - 0.5])
            linear_extrude(1)
                text("iphone_15_pro_fixture", size=5, halign="center", valign="center");
    }
}

// Render
fixture();
